### ISSUE TITLE
Suggestion: Support transparency

### ISSUE THREAD

**Issue by torrobinson** [NotNotWrongUsually/OutConsolePicture#5]
Just a suggestion: if the imported image has a pixel with any amount of transparency, it'd be cool if that pixel translated to an empty character or space when being output to the console - this would allow small icons or pngs with a transparent background to render without a black box around them.

**Comment by NotNotWrongUsually** [comment]
Currently working on supporting proper alpha blending. WIP example here: https://imgur.com/a/VW44aNz

Alas, sometimes the kingdom is lost for want of a nail. In order to do proper blending I have to know the current background colour of the terminal. Powershell itself will report the console colour, but the actual colour is only know to the terminal application. It _should_ be retrievable  with ANSI escape codes, but the relevant ones are not implemented in the Windows console yet (https://github.com/microsoft/terminal/issues/3718).

Going to mull over this for a little longer.

**Comment by torrobinson** [comment]
I think I also looked into this a year ago and gave up very quickly 😆

I suppose at worst, if blending is enabled via a parameter, you could force the user to also provide the _known_ background color as a parameter, but that might be too clunky.

Interested to see what you come up with!

**Comment by NotNotWrongUsually** [comment]
I've done exactly that in the current "positioning" branch. Can force a transparency color by parameter, or it will just default to _my_ console background right now (works on my machine!). This is the One Half Dark theme from Windows Terminal, so it will work for at least a tiny amount of other people too without setting anything! It is basically a placeholder while I try to figure out some way to get the terminal background color. Not too hopeful on that right now.

It will automatically detect if blending is relevant, and only apply it where useful, so there is no parameter on whether to activate it or not.

**Comment by NotNotWrongUsually** [comment]
Merged, and released on the gallery as v.1.6. I'll watch for Terminal getting update with proper support for retrieving bg colour via OSC calls.
